### PR TITLE
Fix a build error on OpenIndiana

### LINKED ISSUE #352: Another build failure on OpenIndiana
```
$ make V=1
Making all in src
make[1]: Entering directory '/home/ruben/src/burp/src'
make  all-am
make[2]: Entering directory '/home/ruben/src/burp/src'
g++ -DHAVE_CONFIG_H -I.   -DSYSCONFDIR=\"/usr/local/etc\"    -g -O2 -MT server/protocol1/burp-blocklen.o -MD -MP -MF server/protocol1/.deps/burp-blocklen.Tpo -c -o server/protocol1/burp-blocklen.o `test -f 'server/protocol1/blocklen.c' || echo './'`server/protocol1/blocklen.c
server/protocol1/blocklen.c: In function ‘size_t get_librsync_block_len(const char*)’:
server/protocol1/blocklen.c:17:31: error: call of overloaded ‘sqrt(uint64_t&)’ is ambiguous
  ret=(size_t)(ceil(sqrt(oldlen)/16)*16); // round to a multiple of 16.
                               ^
server/protocol1/blocklen.c:17:31: note: candidates are:
In file included from /usr/include/math.h:32:0,
                 from server/protocol1/blocklen.c:4:
/usr/include/iso/math_iso.h:218:21: note: long double std::sqrt(long double)
  inline long double sqrt(long double __X) { return __sqrtl(__X); }
                     ^
/usr/include/iso/math_iso.h:186:15: note: float std::sqrt(float)
  inline float sqrt(float __X) { return __sqrtf(__X); }
               ^
/usr/include/iso/math_iso.h:85:15: note: double std::sqrt(double)
 extern double sqrt __P((double));
               ^
Makefile:2602: recipe for target 'server/protocol1/burp-blocklen.o' failed
make[2]: *** [server/protocol1/burp-blocklen.o] Error 1
make[2]: Leaving directory '/home/ruben/src/burp/src'
Makefile:583: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ruben/src/burp/src'
Makefile:431: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

### PR DESCRIPTION
**Pull request by rubenk**
Fixes #352

### CODE REVIEW

**Comment by rubenk** [comment]
Very strange, I did comment as well but it's all gone.

Same error when doing
`ret=(size_t)(ceil((sqrt(oldlen))/16)*16);`

The issue I think is that C++ doesn't have an overloaded sqrt for integral types.
Since oldlen is site_t it tries to decide between std::sqrt(double) and std::sqr(float) and can't make a choice. Does that make sense?

**Comment by rubenk** [comment]
I now see that I made a typo and was supposed to cast oldlen to double.
With this fixes, the test passes and I verified that I get the same result before and after this commit.

**Comment by grke** [comment]
Now fixed in master.

**Comment by rubenk** [comment]
Great, thank you.

**Pull request closed without merging**
