### PR TITLE
253: 'logic' rules parser with new exclude_logic option

### PR DESCRIPTION
**Pull request by ziirish**
Hello,

Here is the patch to support the 'exclude_logic' option as requested in #253 
This is still a Work In Progress, I'll let you know when this is complete. I just wanted you to be able to start reviewing this *huge* patch.

Here is the list of things to be done before considering this PR complete:

- [x] unit tests
- [x] update the documentation

I tried to stick with your coding style as most as I could, besides my C is probably not as good as yours (I haven't really practice it for a while) so feel free to let me know if you notice anything that bothers you.

I ran my tests through valgrind so I think I get rid of the memory leaks even though some data manipulations were complex (like evaluating and factorizing the expressions).

```
$ valgrind ./burp -c /tmp/burp-server.conf
==20391== Memcheck, a memory error detector                                
==20391== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==20391== Using Valgrind-3.12.0.SVN and LibVEX; rerun with -h for copyright info
==20391== Command: ./burp -c /tmp/burp-server.conf
==20391==                                                             
------------------------------------                                    
'file_size<10Kb or file_ext=so' with filename: burp.c, size: 10485760 => 0
'file_size>5Mb and file_ext=so' with filename: burp.c, size: 10485760 => 0
'file_size>5Mb and file_match=burp' with filename: burp.c, size: 10485760 => 1
'file_size<10Kb or file_ext=so' with filename: burp.c, size: 10485760 => 0
'file_size>=10Mb and (file_ext=ost or file_ext=pst)' with filename: burp.c, size: 10485760 => 0
'file_size>=10Mb and not (file_ext=ost or file_ext=pst)' with filename: burp.c, size: 10485760 => 1
'file_size<5Mb or (file_match=.*\..* and not (file_ext=c or file_ext=ost))' with filename: burp.c, size: 10485760 => 0
------------------------------------
------------------------------------
'file_size<10Kb or file_ext=so' with filename: mail.ost, size: 52428800 => 0
'file_size>5Mb and file_ext=so' with filename: mail.ost, size: 52428800 => 0
'file_size>5Mb and file_match=burp' with filename: mail.ost, size: 52428800 => 0
'file_size<10Kb or file_ext=so' with filename: mail.ost, size: 52428800 => 0
'file_size>=10Mb and (file_ext=ost or file_ext=pst)' with filename: mail.ost, size: 52428800 => 1
'file_size>=10Mb and not (file_ext=ost or file_ext=pst)' with filename: mail.ost, size: 52428800 => 0
'file_size<5Mb or (file_match=.*\..* and not (file_ext=c or file_ext=ost))' with filename: mail.ost, size: 52428800 => 0
------------------------------------
------------------------------------
'file_size<10Kb or file_ext=so' with filename: mail.log, size: 209715200 => 0
'file_size>5Mb and file_ext=so' with filename: mail.log, size: 209715200 => 0
'file_size>5Mb and file_match=burp' with filename: mail.log, size: 209715200 => 0
'file_size<10Kb or file_ext=so' with filename: mail.log, size: 209715200 => 0
'file_size>=10Mb and (file_ext=ost or file_ext=pst)' with filename: mail.log, size: 209715200 => 0
'file_size>=10Mb and not (file_ext=ost or file_ext=pst)' with filename: mail.log, size: 209715200 => 1
'file_size<5Mb or (file_match=.*\..* and not (file_ext=c or file_ext=ost))' with filename: mail.log, size: 209715200 => 1
------------------------------------
==20391==
==20391== HEAP SUMMARY:
==20391==     in use at exit: 0 bytes in 0 blocks
==20391==   total heap usage: 675 allocs, 675 frees, 39,495 bytes allocated
==20391==
==20391== All heap blocks were freed -- no leaks are possible
==20391==
==20391== For counts of detected and suppressed errors, rerun with: -v
==20391== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

### CODE REVIEW

**Comment by ziirish** [comment]
I have now added tests for the 'exclude_logic' option and fixed some edges cases while writing the tests.

I have some compilation warnings however, maybe you can give me a hint on why they are appearing:

```
In file included from src/client/main.c:20:0:
src/client/find_logic.h:5:58: warning: ‘struct FF_PKT’ declared inside parameter list will not be visible outside of this definition or declaration
 extern int is_logic_excluded(struct conf **confs, struct FF_PKT *ff);
                                                          ^~~~~~
src/client/find_logic.h:6:58: warning: ‘struct FF_PKT’ declared inside parameter list will not be visible outside of this definition or declaration
 extern int is_logic_included(struct conf **confs, struct FF_PKT *ff);
                                                          ^~~~~~
```

I think this is due to the lack of definition for the `struct stat` which is part of the `FF_PKT` struct in my header files, but I don't understand why you are not seeing those warnings in the *find.h* file itself.


Also, I might need to add some checks/hardening on the `exclude_logic` syntax because having for instance `exclude_logic=file_size=10 or (file_size>15 and file_size<20` (note the missing `)`) might crash your client.

**Comment by ziirish** [comment]
I have now documented the `exclude_logic` option, but while finding some examples, I noticed I may have to rework the parser because some regex are not supported right now (example: 'perso(nnal)?').

Do you think this is a blocker or can we introduce the `exclude_logic` feature as is right now and improve the parser later?

**Comment by grke** [comment]
I think that find.h is included in find.c before it uses FF_PKT. FF_PKT is defined in find.h, so compilation of find.c has no warnings.
Therefore, things using find_logic.h also need to include find.h before find_logic.h.
It may be possible just to include find.h inside find_logic.h.

**Comment by grke** [comment]
I think it is best to fix the problem now, otherwise people could start using it.
At that point, things become harder because you have to keep supporting the previous syntax, or deliberately break it.

**Comment by grke** [comment]
I haven't been able to look at the patch properly yet, but it looks like you've put a lot of effort in, thanks!

**Comment by ziirish** [comment]
> Therefore, things using find_logic.h also need to include find.h before find_logic.h.
> It may be possible just to include find.h inside find_logic.h.

I did include find.h before find_logic.h in find_logic.c, but I also included find_logic.h in src/client/main.c because I need to clean things up after the backup (I use a uthash structure to cache the already parsed expressions) so maybe the warnings came from that include.
Anyway, including find.h inside find_logic.h did fix the issue, if that's OK for you I'll let it that way.

> I think it is best to fix the problem now, otherwise people could start using it.
> At that point, things become harder because you have to keep supporting the previous syntax, or deliberately break it.

Well, the "fix" would actually be an enhancement of the current implementation so this should not break anything, it'll just allow people to have more complete regex.
But I'll try to fix it before the next release so this should not be a problem for anyone.

> it looks like you've put a lot of effort in, thanks!

This was actually a fun problem to solve. I used to love C programming, I just don't have the chance to play with it that often hence the time it took me to properly implement this feature.

**Comment by ziirish** [comment]
I think I have now fixed all the issues:

- no more compilation warnings
- support for escaped whitespaces and parentheses. Ex: `file_match="(a|A).*"`

**Comment by ziirish** [comment]
I have just pushed a fix that prevent the client from crashing when entering unvalid expressions.

**Comment by ziirish** [comment]
I have now implemented the 'path_match' function

**Comment by grke** [comment]
Cool, will look again when I have a chance.
I am getting a bit slowed down by many (non-burp) things at the moment.

**Comment by grke** [comment]
Looks like travis is failing because something is segfaulting in test_find.c.
It passes OK on my workstation.
I'm going to send your changes through my own automated system, to see what happens.

**Comment by ziirish** [comment]
Oh, sorry, I didn't notice. The tests were running fine on my development machine too. I'll double check that when I have a moment.

**Comment by grke** [comment]
Full backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x080965e4 in list_reset (list=<optimized out>) at src/client/find_logic.c:154
154             if(!l || l->len==0) return;
(gdb) bt
#0  0x080965e4 in list_reset (list=<optimized out>)
    at src/client/find_logic.c:154
#1  0x08096ec6 in eval_expression (
    expr=0x4 <error: Cannot access memory at address 0x4>, 
    filename=0xa <error: Cannot access memory at address 0xa>, 
    filesize=<optimized out>, def=0) at src/client/find_logic.c:644
#2  0x08097db5 in is_logic (def=0, miss=0, ff=0x81463b0, list=<optimized out>)
    at src/client/find_logic.c:680
#3  is_logic_excluded (confs=0x8146430, ff=0x81463b0)
    at src/client/find_logic.c:687
#4  0x08095109 in my_send_file_w (asfd=0x4, ff=0x81463b0, top_level=false, 
    confs=0x8146430) at src/client/find.c:291
#5  0x080954fb in found_regular_file (top_level=<optimized out>, 
    confs=<optimized out>, ff_pkt=<optimized out>, asfd=<optimized out>)
    at src/client/find.c:336
#6  find_files (asfd=0x4, ff_pkt=0x81463b0, confs=0x8146430, 
    fname=0x81485a0 "/home/grke/burp-2.2.10/utest_find/a", 
    parent_device=<optimized out>, top_level=false) at src/client/find.c:655
#7  0x08095a0b in process_entries_in_directory (our_device=<optimized out>, 
    ff_pkt=<optimized out>, confs=<optimized out>, link_len=<optimized out>, 
    len=<optimized out>, link=<optimized out>, count=<optimized out>, 
    nl=<optimized out>, asfd=<optimized out>) at src/client/find.c:463
#8  found_directory (top_level=<optimized out>, parent_device=<optimized out>, 
    fname=<optimized out>, confs=<optimized out>, ff_pkt=<optimized out>, 
    asfd=<optimized out>) at src/client/find.c:592
#9  find_files (asfd=0x4, ff_pkt=0x8147e80, confs=0x8146430, 
    fname=0x8147a60 "\200~\024\b\240z\024\b ~\024\b0~\024\b`~\024\b\220z\024\b\020~\024\bp~\024\b@~\024\bP~\024\bpdȷ\021", parent_device=<optimized out>, 
    top_level=true) at src/client/find.c:678
#10 0x08095bb3 in find_files_begin (asfd=<optimized out>, 
    ff_pkt=<optimized out>, confs=<optimized out>, fname=<optimized out>)
    at src/client/find.c:687
#11 0x08058479 in run_find (confs=0x8146430, ff=0x81463b0, 
    buf=0xbfffe4a0 "mode=client\nserver=4.5.6.7\nlockfile=/lockfile/path\nssl_cert=/ssl/cert/path\nssl_cert_ca=/cert_ca/path\nssl_peer_cn=my_cn\nca_csr_dir=/csr/dir\nssl_key=/ssl/key/path\nport=1234\nstatus_port=12345\ninclude=/ho"...)
    at utest/client/test_find.c:194
#12 do_test (setup_entries=0x80580b0 <exclude_logic>)
    at utest/client/test_find.c:212
#13 0x080cba51 in tcase_run_tfun_nofork.isra ()
#14 0x080cbcf5 in srunner_run ()
#15 0x080cc333 in srunner_run_all ()
#16 0x0804d754 in main () at utest/main.c:17
(gdb) 
```

**Comment by grke** [comment]
^ I got that backtrace on caacrinolas (i386 machine), if you need to be able to reproduce it.

**Comment by ziirish** [comment]
I'm not sure I have access to this VM but I'll see what I can do with that backtrace. Thanks

**Comment by grke** [comment]
Cool, travis is fixed. I will run it through my tests again.

**Comment by grke** [comment]
Got some Windows compilation errors. Basically, all the places in src/handy.c that do a malloc_w() have to cast the 'void *' to a 'char *' or a 'char **'. Like this:
```
-                                       tmp=malloc_w(tmp_len, func);
+                                       tmp=(char *)malloc_w(tmp_len, func);
```

**Comment by grke** [comment]
Running it through again with those changes.

**Comment by grke** [comment]
Problem - can't build for Windows because it doesn't have uthash.h:
```
/burp/test/build/src/client/find_logic.c:12:10: fatal error: uthash.h: No such file or directory
```

Up to now, I have only needed uthash.h for non-Windows.
To make this work, we will have to add uthash.h to the Windows dependencies in https://github.com/grke/burp-cross-tools

**Comment by grke** [comment]
I am now attempting to add uthash.h to the Windows dependencies.

**Comment by ziirish** [comment]
Thanks for the troubleshooting.
If this is too complicated, We can just disable the cache part on Windows for now and see if there is a real benefit for it.

Currently, I use two distinct caches: one for the `*_match` regexp so we don't have to compile them for every file, and one to convert the `expressions` in tokens (so it's just a "split").

**Comment by grke** [comment]
Windows build uses the C++ compiler, where 'new' is a reserved word, and it is also upset about size_ts being compared to ints.

**Comment by grke** [comment]
I have it working now. I will merge your things, and apply my fixes on top.

**Comment by grke** [comment]
Fixes now in master.

**Pull request merged**
