### PR TITLE
Feature/network access control

### PR DESCRIPTION
**Pull request by piligrim773**
Added network access control at the burp level

New server configuration file options:
allow, allow_status - control access to the server sockets

New client configuration file options:
client_allow - control access per cname

### CODE REVIEW

**Comment by grke** [comment]
Thank you, I will look at this soon.

**Comment by grke** [comment]
Hello,

This fails my freebsd test build:

```
  CC       src/server/protocol1/vss_strip-vss_strip.o
  CCLD     vss_strip
  CC       src/main-alloc.o
  CC       src/main-asfd.o
In file included from src/asfd.h:8,
                 from src/asfd.c:3:
src/ipacl.h:20:10: fatal error: linux/types.h: No such file or directory
 #include <linux/types.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
*** Error code 1
```

**Comment by grke** [comment]
Maybe I didn't grab your latest changes, I will try again.

**Comment by grke** [comment]
Hello,
Thank you for this, it passes all my tests.
I am going to merge it, but I will do a couple of slight tweaks on top. For example, I think the names of the configs should be a little bit more descriptive.
For example, "allow_network" instead of "allow".
And, I think the manpage should mention what happens if you don't set these options.

**Comment by grke** [comment]
Will make it "network_allow" and "network_allow_status".

Also, "client_allow" isn't needed, because you can just override the two other options as required inside the client-specific files.
Will also make the options 'strlists' instead of plain strings, so you can do:

network_allow = ::1
network_allow = 10.0.0.2
etc.

**Comment by dmitry-sinina** [comment]
>Also, "client_allow" isn't needed, because you can just override the two other options as required inside the client-specific files.

We specially created different config variables **allow** and **client_allow** because **allow** applies to socket on connection establishment phase, but client_allow checks CN name during TLS negotiation so this is completely different mechanisms. Will not same names for different mechanism confuse user?

**Comment by dmitry-sinina** [comment]
So it is not possible to redefine **allow** with **client_allow** per client - it will be not possible to check TLS CN, because connection will be dropped earlier. But it is possible to add global **client_allow** variable and per client config will redefine it.

**Comment by grke** [comment]
Hello,

I think multiple different configs are more confusing than fewer configs.

You would put the more permissive config in the burp-server.conf (eg, network_allow=10.0.0.0/24), and the more restrictive in individual clientconfig files (eg, network_allow=10.0.0.232), and everything ought to work as you might expect.

I have done all the changes I talked about above a few days ago, but have yet to test them to make sure it works (or to confirm that it doesn't - maybe I am just wrong).
I should get round to test it soon.

**Comment by grke** [comment]
I tested my changes, it all works as expected.

I found that the status monitor option wasn't working correctly - the normal allow option would kick in instead on status connections, but I have updated the code to fix that too.

Will probably push this later today.

**Pull request merged**
