### PR TITLE
Autotools cleanup

### PR DESCRIPTION
**Pull request by rubenk**
Hi Graham,

Here are some more cleanups. Let me know if you have any comments, and if I should keep going.
Looking at configure.ac there's a bit more work to do ;)

### CODE REVIEW

**Comment by grke** [comment]
Hello,

Thanks for this...

Unfortunately, your first change (which I already merged) is breaking builds on freebsd in my test environment.

It can no longer find uthash. Here is the configure line that I use:
./configure --prefix=/usr/local --sbindir=/usr/local/sbin LDFLAGS="-L/usr/local/lib"

The output ends like this:

checking for crypt.h... no
checking for crypt in -lcrypt... yes
checking uthash.h usability... no
checking uthash.h presence... no
checking for uthash.h... no
Please install uthash


config.log has this message:


configure:21922: result: no
configure:21922: checking for crypt.h
configure:21922: result: no
configure:21932: checking for crypt in -lcrypt
configure:21957: cc -o conftest -g -O2  -L/usr/local/lib conftest.c -lcrypt   >&
5
configure:21957: $? = 0
configure:21966: result: yes
configure:21983: checking uthash.h usability
configure:21983: cc -c -g -O2  conftest.c >&5
conftest.c:176:10: fatal error: 'uthash.h' file not found
#include <uthash.h>
         ^
1 error generated.


I then tried the configure line:
./configure --prefix=/usr/local --sbindir=/usr/local/sbin LDFLAGS="-L/usr/local/lib" "CFLAGS=-I/usr/local/include"
And this worked, although configure complained about not being able to find librsync.h (which is also in /usr/local/include). But 'gmake' was then able to compile burp successfully anyway.
I will add the extra argument to my freebsd script.

I am not very good with automake and friends. Do you know of a way of making the configure line simpler for freebsd?

**Comment by grke** [comment]
Also, there is this in the issues list:

https://github.com/grke/burp/issues/266

**Comment by rubenk** [comment]
That's interesting, I made these changes on FreeBSD :)
What I did was ./configure CPPFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib".
CPPFLAGS because libtool already ads CFLAGS to linker commands. Does that work for you?

I certainly know how to make configure simpler, but it's going to take some more changes, I guess a lot is just leftovers from the Bacula days?

Two questions though,
- Any objections to switching to automake?
- The C code is compiled with a C++ compiler, is this on purpose?

**Comment by grke** [comment]
Your simpler configure arguments worked nicely, thank you. :)

Yes, when I first created burp, I copied bacula and deleted all the stuff that I didn't want.
Since I don't understand configure very well, I didn't know how to make it much better.

I have no objections to switching to automake, as long as it doesn't break my automatic builds.

Bacula has a lot of C++ in it, including the win32 compatibility stuff.
In burp, most of the code is C, but some of the win32 stuff is still C++.
About a year ago, I attempted to switch to using pure C and the C compiler.
However, my attempt failed for some reason that I can't remember and
I stayed using the C++ compiler.

**Comment by rubenk** [comment]
Ah, great :)
I just opened another pull request, which contains the commits from this PR as well (348)
Here we now also detect the correct paths on FreeBSD, so no need to adjust your scripts.

I tried compiling with a C compiler, but we use some C++ stuff (struct BFILE iirc). Not much, but I'll leave it alone for now.

Converting to automake was more work than I thought, but I should be done in a few days.
I can't get the test suite (utest) to run on Fedora 23, but this is also the case on master.
Also looking into the mingw stuff, but I got stuck on trying to build your crossbuild tools somewhere in binutils.

**Comment by grke** [comment]
Is it worth me testing the changes in this pull request, or should I go straight to your most recent set?

With this patch set on my desktop (arch linux), I run:
autoconf
./configure

and I get:

checking for pidof... /usr/bin/pidof
checking for gawk... gawk
checking for gawk... /usr/bin/gawk
./configure: line 5628: syntax error near unexpected token `shared'
./configure: line 5628: `LT_INIT(shared disable-static)'

Maybe autoconf is the wrong thing to run?

**Comment by rubenk** [comment]
Btw, I didn't know much autotools either a while ago, but once I read Autotools: A Practioner's Guide to GNU Autoconf, Automake, and Libtool by John Calcote, it all made sense. If you want to learn more I highly recommend it!

**Comment by rubenk** [comment]
ah yes, you need autoreconf, not autoconf. `autoreconf -vif` is what I do.

**Pull request closed without merging**
