### PR TITLE
Fix a lot of -Wformat warnings

### PR DESCRIPTION
**Pull request by rubenk**
Also fixes a segfault in one of the tests on NetBSD

### CODE REVIEW

**Comment by grke** [comment]
Hello,
Some of these don't look correct.
For example:

```
-		logc("% 9s ", "");
-		logc("% 9s ", "");
-		logc("% 9llu\n", e);
+		logc("%9s ", "");
+		logc("%9s ", "");
+		logc("%9" PRIu64 "\n", e);
```

"% 9s" is supposed to pad with spaces.
I think my automatic tests are failing too since the printf attributes patch, though I can't get home to check what is going on until about 10 hours from now. I guess that this patch is intended to fix that.

**Comment by grke** [comment]
Ah, I think I was confused. It is probably all OK.

**Comment by rubenk** [comment]
Hi Graham,

Indeed, %9s already aligns right-aligns and pads with spaces.
%space is only defined for signed numbers, for all other conversion specificiers it is undefined behaviour.

**Comment by rubenk** [comment]
The one thing I'm not sure about is if https://github.com/rubenk/burp/commit/e8b0c71fc7a97828a63d662648e3513aced27074#diff-bef90e3fdf84e6b35e1d9781e3b9311eR514 is correct.

**Comment by grke** [comment]
I think that is correct.

**Comment by grke** [comment]
I'm having trouble with 64bit Windows and %zu:

/home/ubuntu/burp-2.0.30/src/protocol1/msg.c: In function ‘int do_write(asfd*, BFILE*, uint8_t*, size_t, char**, uint64_t*)’:
/home/ubuntu/burp-2.0.30/src/protocol1/msg.c:38:54: error: unknown conversion type character ‘z’ in format [-Werror=format]
/home/ubuntu/burp-2.0.30/src/protocol1/msg.c:38:54: error: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘size_t {aka long long unsigned int}’ [-Werror=format]
/home/ubuntu/burp-2.0.30/src/protocol1/msg.c:38:54: error: too many arguments for format [-Werror=format-extra-args]

Strangely, 32bit Windows is happy.

**Comment by grke** [comment]
I am merging this patch, and will attempt to fix up the problems.

**Comment by grke** [comment]
The Windows problems are now fixed in master.

**Comment by rubenk** [comment]
Great, thanks. Strange that Windows still doesn't have %zu for printing size_t.

**Pull request merged**
