### PR TITLE
Update burp.spec

### PR DESCRIPTION
**Pull request by kaptk2**
SPEC file as accepted into EPEL, builds for both systemd and init based systems

### CODE REVIEW

**Comment by grke** [comment]
Hello,

Thanks for your request.
Branch master is for burp-2 stuff, which I think isn't appropriate for this spec file.
Can you do another request on branch 1.4-master?

**Comment by kaptk2** [comment]
Opps sorry. I didn't realize that I pulled against master. I'll redo

**Comment by kaptk2** [comment]
My other pull request that added systemd capability was merged against master as well, just an FYI

**Comment by grke** [comment]
Thanks, I didn't realise that the previous one was for a different version at the time.

Basically, master: 2.0.x, 1.4-master: 1.4.x, and 1.3-master: 1.3.x.

**Comment by grke** [comment]
Oops, I thought this one was now on 1.4-master, so I merged it, then noticed, then reverted it.

**Pull request merged**
