### PR TITLE
Fixes to compile with a C compiler

### PR DESCRIPTION
**Pull request by rubenk**
Nothing out of the ordinary, just added some missing includes
for things like 'bool', a few typedefs here and there (which we should
clean up later) and fixed some things which are allowed in C++ but not
in C.

Still a lot of warnings, and I haven't checked if it builds on Windows.

### CODE REVIEW

**Comment by grke** [comment]
Haha, nice work! Thanks a lot.


It passes the runner stuff first time for me on Debian.
I will try to run it through my full testing system (includes BSDs and Windows) and see what happens...
This may take a little while.

**Comment by grke** [comment]
I didn't get as far as Windows - it locked up on my Debian machine on protocol 1 test 14 when I did this:

git clean -fdx
autoreconf -vif
cd test
make test

It seems to go into a tight CPU loop in librsync-related code.

**Comment by grke** [comment]
I figured out the problem.
Some burp functions in src/protocol1/rs_buf.c are named the same as some functions in librsync, and it screws things up.
I am bypassing the problem now, by changing rs_loadsig_fzp to look like this:

```
rs_result rs_loadsig_fzp(struct fzp *fzp,
        rs_signature_t **sig, rs_stats_t *stats)
{
        rs_result r;
        rs_job_t *job;

        job=rs_loadsig_begin(sig);
        r=rs_whole_gzrun(job, fzp, NULL);
        rs_job_free(job);

        return r;
}
```

**Comment by rubenk** [comment]
Heh, interesting. So the burp code is called and not the librsync code, causing the loop?
If the functions really are the same I'd have expected the linker to catch that, but perhaps not.

**Comment by rubenk** [comment]
Closing this in favor of #462, which takes a simpler approach.

**Pull request closed without merging**
