### PR TITLE
Osx selftests

### PR DESCRIPTION
**Pull request by rubenk**

### CODE REVIEW

**Comment by grke** [comment]
Doesn't the change to the configure options in build_and_install break tests on everything that isn't OSX?

**Comment by rubenk** [comment]
Oops, I didn't mean to include that chunk. I'll fix that up.

**Comment by rubenk** [comment]
Fixed and rebased.

**Comment by grke** [comment]
Does the change to the flock line mean that I can close issue #361?

**Comment by rubenk** [comment]
This works for now but people still need to build the portable flock from that git repo. I'd rather use something which exists on all platforms. Let me look into it.

**Comment by rubenk** [comment]
I dropped the first patch, a better solution is in PR #372

**Comment by grke** [comment]
Thank you.

**Comment by grke** [comment]
Hello,
The sed changes have broken my Windows tests (ie, test/test_windows64). I haven't had time to figure out precisely why yet. Probably something is appending to the conf file rather than replacing a setting.
I will possibly end up reverting the sed changes in order to get other changes in.

**Comment by grke** [comment]
The problem was actually the change to set the server listen address to 127.0.0.1.
It means that the Windows client cannot connect to it during the test cycle.
So, I just pushed a change to revert that.

**Comment by rubenk** [comment]
Ah! Any idea why the client can't connect? Is it not running on the same host?

**Comment by grke** [comment]
You cannot run a burp server on a Windows machine.
So, the test sets up a burp server on a ubuntu machine, and a client on a Windows machine.

**Pull request merged**
