### PR TITLE
Fixes #610

### LINKED ISSUE #610: Windows scheduled task won't work when not plugged in
Hello,

Burp fits especially well for laptop users, since it tries to backup every 20 minutes which is perfect for people that carry a laptop and use it without any special schedule.

I noticed that the scheduled task the windows installer creates is marked not to run if the computer works on battery. Since backups should always run, I do think this default behavior should be changed to run the scheduled task in any case.

Best regards,
Ozy.

### PR DESCRIPTION
**Pull request by deajan**
This is a workaround for using schtasks executable, which doesn't have the ability to override power settings when creating a new task preventing to run the task when a laptop isn't plugged in.

### CODE REVIEW

**Comment by ZungBang** [comment]
I find the default behavior to be perfectly reasonable. I don't want a backup to fail because the laptop died in mid backup. I also wouldn't appreciate the laptop dying on me for no apparent reason. 

Bottom line, opinions may differ, and this change would surprise other users. So maybe the right thing to do is add another option to the installer instead of imposing a new default behavior on everyone.

My 2c.

**Comment by deajan** [comment]
With laptops having 10h or more batteries, I see users that only connect the laptop when resting, thus having no backups, or rarely. I'd rather have half of all backed up files, than none.

But you have a point about the default behavior change.
I'd love to know Graham's thoughts here, since I think the linux version using cron doesn't mess with power mode to run or not the backup :)

Maybe adding a /usepowermode switch to the NSIS installer would be the right thing to do. Or a /nopowermode if the earlier default behavior has to be kept.

I can mod my PR accordingly.

**Comment by grke** [comment]
Hello,

Thanks for the patches and comments.
I would like to keep the previous behaviour by default, so as not to surprise people.
Having a switch to NSIS to enable backups whilst on a battery is great though.

**Comment by deajan** [comment]
Okay, I'll try to add this to this PR soon.

**Comment by grke** [comment]
Hello,
I ran the changes through my automatic testing system, but the nsis installer failed to build:

```
----------------------------------------------------------------------
NSIS String Functions Header File 1.09 - Copyright 2004 Diego Pedroso
----------------------------------------------------------------------
 (/home/ubuntu/burp-2.1.18/test/build/src/win32/../../burp-depkgs/mingw-w64-x86_64/nsis/Include/StrFunc.nsh:52)
!include: could not find: "StrRep.nsh"
Error in script "winburp.nsi" on line 12 -- aborting creation process
make[1]: Leaving directory `/home/ubuntu/burp-2.1.18/test/build/src/win32/installer64'

!!!!! Make of installer64 failed !!!!!
```

**Comment by grke** [comment]
Also "burp_task.xml" is kind of breaking the fully-genericised winburp.nsi file.
It think it should be "${PACKAGE_TARNAME}_task.xml", or some non-package specific name like "timer_task.xml".

**Comment by deajan** [comment]
I still don't have access to my build setup for some days, I'll check the PR in a couple of days.

**Comment by deajan** [comment]
Finally had time to get to my build setup.
I've added a GUI option too.
PR has been tested for both win32 and win64 platforms and works for me.

**Comment by grke** [comment]
Nice work, it now builds and passes all my automatic tests.
I will take a manual look at the new installer screen later today, hopefully.

**Comment by grke** [comment]
All fine, merging. Thanks!

**Pull request merged**
