### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by rubenk**
This is based on #457 so that one should be merged first.

### CODE REVIEW

**Comment by grke** [comment]
On linux i386, I get strange segfaults in 'make runner && ./runner'.

For example, in test_attribs, it ends up calling sbuf_alloc(PROTO_2), and then tries to access sbuf->protocol2->index.

Inside sbuf_alloc(), sbuf->protocol2 is assigned, but after sbuf_alloc() returns, sbuf->protocol2 is NULL.

I have no idea how this can be possible.

**Comment by rubenk** [comment]
(You know you can just run `make check` right?)

Strange, I haven't tested i386 yet, but tests still pass on x86_64.

**Comment by grke** [comment]
64 bit all works great for me.
The 32 bit was already broken in your first patchset, not specific to this patchset that I am commenting on.
It's a really strange thing that I don't think I have ever seen before.

**Comment by rubenk** [comment]
Ok, I'll try to figure out what's wrong.

**Comment by rubenk** [comment]
I see the segfaults too, on CentOS 6 i386.

Btw, running master on that machine has test failures too, is that a known issue?
```
94%: Checks: 318, Failures: 16, Errors: 0
utest/client/test_extrameta.c:100:F:Core:test_extrametas:0: Assertion 'has_extrameta(path, cmd, 1, 1 )==0' failed
utest/client/protocol2/test_rabin_read.c:79:F:Core:test_rabin_read:0: Assertion 'has_xattr(sb->path.buf)==0' failed
utest/client/test_xattr.c:148:F:Core:test_xattrs:0: Assertion 'has_xattr(path)==0' failed
utest/test_fzp.c:98:F:Core:test_fzp_gzseek:0: Assertion '!fzp_seek(fzp, d->pos, SEEK_SET)' failed
utest/server/test_manio.c:213:F:Core:test_man_protocol1_tell_seek:0: Assertion '!manio_seek(manio, offset)' failed
utest/server/test_manio.c:213:F:Core:test_man_protocol2_tell_seek:0: Assertion '!manio_seek(manio, offset)' failed
utest/server/test_manio.c:213:F:Core:test_man_protocol1_phase1_tell_seek:0: Assertion '!manio_seek(manio, offset)' failed
utest/server/test_manio.c:213:F:Core:test_man_protocol2_phase1_tell_seek:0: Assertion '!manio_seek(manio, offset)' failed
utest/server/test_manio.c:213:F:Core:test_man_protocol1_phase2_tell_seek:0: Assertion '!manio_seek(manio, offset)' failed
utest/server/test_manio.c:213:F:Core:test_man_protocol2_phase2_tell_seek:0: Assertion '!manio_seek(manio, offset)' failed
utest/server/test_resume.c:240:F:Core:test_man_protocol1_phase2_get_last_good_entry:0: Assertion '!manio_seek(manio, pos)' failed
utest/server/test_resume.c:240:F:Core:test_man_protocol2_phase2_get_last_good_entry:0: Assertion '!manio_seek(manio, pos)' failed
utest/server/test_resume.c:464:F:Core:test_man_protocol1_phase2_forward_past_entry:0: Assertion '!manio_seek(manio, pos)' failed
utest/server/test_resume.c:464:F:Core:test_man_protocol2_phase2_forward_past_entry:0: Assertion '!manio_seek(manio, pos)' failed
utest/server/test_resume.c:670:F:Core:test_man_protocol1_phase2_forward_before_entry:0: Assertion '!manio_seek(manio, pos)' failed
utest/server/test_resume.c:670:F:Core:test_man_protocol2_phase2_forward_before_entry:0: Assertion '!manio_seek(manio, pos)' failed
FAIL: runner
```

**Comment by rubenk** [comment]
Ok, a few of those are me having SELinux enabled. With that off I get:
```
95%: Checks: 318, Failures: 13, Errors: 0
utest/test_fzp.c:98:F:Core:test_fzp_gzseek:0: Assertion '!fzp_seek(fzp, d->pos, SEEK_SET)' failed
utest/server/test_manio.c:213:F:Core:test_man_protocol1_tell_seek:0: Assertion '!manio_seek(manio, offset)' failed
utest/server/test_manio.c:213:F:Core:test_man_protocol2_tell_seek:0: Assertion '!manio_seek(manio, offset)' failed
utest/server/test_manio.c:213:F:Core:test_man_protocol1_phase1_tell_seek:0: Assertion '!manio_seek(manio, offset)' failed
utest/server/test_manio.c:213:F:Core:test_man_protocol2_phase1_tell_seek:0: Assertion '!manio_seek(manio, offset)' failed
utest/server/test_manio.c:213:F:Core:test_man_protocol1_phase2_tell_seek:0: Assertion '!manio_seek(manio, offset)' failed
utest/server/test_manio.c:213:F:Core:test_man_protocol2_phase2_tell_seek:0: Assertion '!manio_seek(manio, offset)' failed
utest/server/test_resume.c:240:F:Core:test_man_protocol1_phase2_get_last_good_entry:0: Assertion '!manio_seek(manio, pos)' failed
utest/server/test_resume.c:240:F:Core:test_man_protocol2_phase2_get_last_good_entry:0: Assertion '!manio_seek(manio, pos)' failed
utest/server/test_resume.c:464:F:Core:test_man_protocol1_phase2_forward_past_entry:0: Assertion '!manio_seek(manio, pos)' failed
utest/server/test_resume.c:464:F:Core:test_man_protocol2_phase2_forward_past_entry:0: Assertion '!manio_seek(manio, pos)' failed
utest/server/test_resume.c:670:F:Core:test_man_protocol1_phase2_forward_before_entry:0: Assertion '!manio_seek(manio, pos)' failed
utest/server/test_resume.c:670:F:Core:test_man_protocol2_phase2_forward_before_entry:0: Assertion '!manio_seek(manio, pos)' failed
```

**Comment by grke** [comment]
I haven't heard of any problems with Centos 6 i386 running the utests, but that is not one that I test automatically, so I would be reliant of other people telling me about that.

The only 32 bit machine I have set up as part of my automated tests is Debian 8.2.

**Comment by rubenk** [comment]
Ok, now trying Fedora 24 i386 and if that doesn't work I'll setup a Debian vm.
Still fighting to properly get debug symbols out of Burp, for some reason -O0 has issues with the `inline IsPathSeparator` function.

**Comment by rubenk** [comment]
All tests pass on Fedora 24 i386. Is it only Debian you're seeing this issue on?

**Comment by grke** [comment]
So far, I have only tried Debian. It's the same on 8.5.
Now installing Centos 6.8 to see.

**Comment by grke** [comment]
I have the same segfaults on Centos 6.8.

**Comment by rubenk** [comment]
This is a very weird issue, it seems to be an alignment problem.

Here's *sb inside sbuf_alloc:
```
(gdb) p *sb
$44 = {
  path = {
    cmd = CMD_ERROR, 
    buf = 0x0, 
    len = 0
  }, 
  link = {
    cmd = CMD_ERROR, 
    buf = 0x0, 
    len = 0
  }, 
  attr = {
    cmd = CMD_ATTRIBS, 
    buf = 0x0, 
    len = 0
  }, 
  endfile = {
    cmd = CMD_ERROR, 
    buf = 0x0, 
    len = 0
  }, 
  statp = {
    st_dev = 0, 
    __pad1 = 0, 
    __st_ino = 0, 
    st_mode = 0, 
    st_nlink = 0, 
    st_uid = 0, 
    st_gid = 0, 
    st_rdev = 0, 
    __pad2 = 0, 
    st_size = 0, 
    st_blksize = 0, 
    st_blocks = 0, 
    st_atim = {
      tv_sec = 0, 
      tv_nsec = 0
    }, 
    st_mtim = {
      tv_sec = 0, 
      tv_nsec = 0
    }, 
    st_ctim = {
      tv_sec = 0, 
      tv_nsec = 0
    }, 
    st_ino = 0
  }, 
  winattr = 0, 
  compression = -1, 
  flags = 0, 
  protocol1 = 0x812a0d8, 
  protocol2 = 0x0, 
  next = 0x0
}
```

And here it is when it is returned:
```
(gdb) p *sbuf
$45 = {
  path = {
    cmd = CMD_ERROR, 
    buf = 0x0, 
    len = 0
  }, 
  link = {
    cmd = CMD_ERROR, 
    buf = 0x0, 
    len = 0
  }, 
  attr = {
    cmd = CMD_ATTRIBS, 
    buf = 0x0, 
    len = 0
  }, 
  endfile = {
    cmd = CMD_ERROR, 
    buf = 0x0, 
    len = 0
  }, 
  statp = {
    st_dev = 0, 
    __pad1 = 0, 
    st_ino = 0, 
    st_mode = 0, 
    st_nlink = 0, 
    st_uid = 0, 
    st_gid = 0, 
    st_rdev = 0, 
    __pad2 = 0, 
    st_size = 0, 
    st_blksize = 0, 
    st_blocks = 0, 
    st_atim = {
      tv_sec = 0, 
      tv_nsec = 0
    }, 
    st_mtim = {
      tv_sec = 0, 
      tv_nsec = 0
    }, 
    st_ctim = {
      tv_sec = 0, 
      tv_nsec = 0
    }, 
    __glibc_reserved4 = 0, 
    __glibc_reserved5 = 0
  }, 
  winattr = 0, 
  compression = 0, 
  flags = 0, 
  protocol1 = 0xffffffff, 
  protocol2 = 0x0, 
  next = 0x812a0d8
}
```

Note the address of ->protocol1, which is now in ->next, and ->compression ended up in ->protocol1

**Comment by grke** [comment]
Looks like the statp is a different shape.
Maybe the sbuf.c source file is including a different definition for the struct stat than the test source file?

**Comment by rubenk** [comment]
That must be it. I double-checked the data in memory:
```(gdb) x/4b ((char *)sb+160)
0x8124b90:	0xd8	0xa0	0x12	0x08
```
it's still there after sbuf_alloc returned:
```
(gdb) x/4b ((char *)sbuf+160)
0x8124b90:	0xd8	0xa0	0x12	0x08
```

**Comment by rubenk** [comment]
Indeed, observe the blkcnt_t field:
```
(gdb) ptype sb->statp
type = struct stat {
    __dev_t st_dev;
    unsigned short __pad1;
    __ino_t __st_ino;
    __mode_t st_mode;
    __nlink_t st_nlink;
    __uid_t st_uid;
    __gid_t st_gid;
    __dev_t st_rdev;
    unsigned short __pad2;
    __off64_t st_size;
    __blksize_t st_blksize;
    __blkcnt64_t st_blocks;
    struct timespec st_atim;
    struct timespec st_mtim;
    struct timespec st_ctim;
    __ino64_t st_ino;
}
```
vs
```
(gdb) ptype sbuf->statp
type = struct stat {
    __dev_t st_dev;
    unsigned short __pad1;
    __ino_t st_ino;
    __mode_t st_mode;
    __nlink_t st_nlink;
    __uid_t st_uid;
    __gid_t st_gid;
    __dev_t st_rdev;
    unsigned short __pad2;
    __off_t st_size;
    __blksize_t st_blksize;
    __blkcnt_t st_blocks;
    struct timespec st_atim;
    struct timespec st_mtim;
    struct timespec st_ctim;
    unsigned long __glibc_reserved4;
    unsigned long __glibc_reserved5;
}
```

**Comment by grke** [comment]
sizeof(struct stat) is either 88 or 96, depending on what source file you are in.

**Comment by grke** [comment]
Got it.

In utest/test.h, put include "utest/builders/server/build_storage_dirs.h" below "sbuf.h".

burp.h needs to be first.

**Comment by grke** [comment]
Same for other segfaulting tests.

**Comment by rubenk** [comment]
Ah, yes, you beat me to it ;)
FILE_OFFSET_BITS=64 needs to be defined, so config.h or burp.h needs to be first indeed.

**Comment by grke** [comment]
I still have segfaults at utest/builders/build_asfd_mock.c:150, but I have to go to sleep now. :)

**Comment by rubenk** [comment]
Alright, probably the same issue and I now know how to fix it.
Sleep well!

**Comment by rubenk** [comment]
Not the same issue it seems, and I can't get gdb to break in that test-suite. I'd appreciate it if you can have a look later.

**Comment by rubenk** [comment]
Closing this in favor of #462. I'll redo the cleanups later once we're satisfied with that PR.

**Pull request closed without merging**
