### PR TITLE
Nsis add guiport

### PR DESCRIPTION
**Pull request by deajan**
Since I have recompiled the NSIS installer earlier, thought it would be nice to add the port as GUI option as burp can use multiple port bindings.

### CODE REVIEW

**Comment by grke** [comment]
I'm attempting to make a 2.1-master branch for bug fixes, and have master be for 2.2 new features.
While I am messing around with getting the branches to work properly, I will leave off merging this.
I am reverting the backup tool patch in 2.1-master branch, and leaving it in master for 2.2.

**Comment by deajan** [comment]
Sure :)

**Comment by deajan** [comment]
Do you think this can be merged by now into master ?

**Comment by grke** [comment]
Sorry for the delay, it is the next thing I will look at after the new windows buildtools, librsync 2 and the strong checksums.

**Comment by grke** [comment]
Thanks, looks good.
I have updated this page with new screenshots: https://burp.grke.org/docs/windows-installer.html

**Pull request merged**
