### PR TITLE
Compile Burp as C

### PR DESCRIPTION
**Pull request by rubenk**
A pretty big diff, but most of it is mechanical due to differences
between C++ and C.

### CODE REVIEW

**Comment by grke** [comment]
I will have another go at fixing the Debian i386 utest segfault when I get a spare moment.

I did have one run at Windows. It had a fatal error:

```
/home/ubuntu/burp-2.0.45/src/client/acl.c:14:21: fatal error: sys/acl.h: No such file or directory
```

And some warnings because of config.h overriding defines from mingwconfig.h:

```
/home/ubuntu/burp-2.0.45/src/win32/compat/mingwconfig.h:322:0: note: this is the location of the previous definition
In file included from /home/ubuntu/burp-2.0.45/src/client/acl.h:6:0,
                 from /home/ubuntu/burp-2.0.45/src/client/acl.c:1:
/home/ubuntu/burp-2.0.45/src/config.h:200:0: error: "PACKAGE_TARNAME" redefined [-Werror]
```

I'll get onto the Windows again once Debian i386 is happy.

**Comment by rubenk** [comment]
All tests in this commit pass for me on i386. I wouldn't spend more time on the other PR.

**Comment by rubenk** [comment]
I also left the header ordering in this commit alone, so both Windows and Debian should be happy :)

**Comment by grke** [comment]
Working great. Just had one minor tweak to get Windows to work, which I'll commit in a moment.

**Comment by grke** [comment]
Done. Thanks a lot!

**Comment by rubenk** [comment]
Great, thanks!

**Pull request merged**
