### PR TITLE
Feature glob after script pre

### PR DESCRIPTION
**Pull request by ziirish**
This should address #342 

Tests passed on my side (except the xattr):

```
99%: Checks: 274, Failures: 2, Errors: 0
utest/client/protocol2/test_rabin_read.c:87:F:Core:test_rabin_read:0: Assertion '!set_xattr( NULL, sb->path.buf, x.write, strlen(x.write), metasymbol, NULL )' failed
utest/client/test_xattr.c:156:F:Core:test_xattrs:0: Assertion '!set_xattr( NULL, path, x.write, strlen(x.write), metasymbol, NULL )' failed

```

### CODE REVIEW

**Comment by grke** [comment]
Here are the little things that I mentioned by email:

*) I would like you to remove the four lines from burp.conf.in. I think in
   99.99% of cases, the code will work fine with the defaults, so it is not
   worth adding extra things to be confused about in the client burp.conf.
   Keep the 'server_can_override_includes=1' change in though.

*) The man page comment isn't quite right. I suggest this:
   "Set this to 0 if you do not want the include_glob settings to be evaluated
   after the pre script is run. The default is 1."

*) I think OPT_INCEXCDIR needs to be freed/cleared at the start of
   reeval_glob(), or duplicate paths could get added to it.

**Comment by grke** [comment]
I have got Travis working now, too. You now have green ticks on your pull request.

**Comment by ziirish** [comment]
I updated the code according to your feedback.

I did not find a nicer/easier way to avoid duplicates in include list though.

**Comment by ziirish** [comment]
I added the missing include_glob documentation and some tests as discussed.

**Comment by grke** [comment]
OK, I will check it soon.
It seems I left some utest debug turned on in the latest release.
I commented out the 'ifndef UTEST' lines in src/log.c, so utest is making far too much output.

**Comment by grke** [comment]
Thanks!

**Pull request merged**
