### PR TITLE
docs: exclude_regex uses PCRE and / delimiters

### PR DESCRIPTION
**Pull request by juodumas**

### CODE REVIEW

**Comment by grke** [comment]
Hello,

Thanks for your pull request, but it is incorrect.
'exclude_regex' has no requirement that it begins and ends with a slash, and it is not necessarily PCRE.

**Comment by juodumas** [comment]
Thanks for the reply. And sorry, didn't look at the code before creating the PR. Then maybe add a sentence like this to the exclude_regex documentation?

    Uses POSIX Extended Regular Expression syntax. Case insensitive on Windows.

Is POSIX Extended also used on Windows?

This example uses slashes as delimiters:
https://github.com/grke/burp/blob/master/configs/server/clientconfdir/incexc/example
Would it work with delimiters and without them? If it's either or, then it would be nice to have it documented.

**Comment by grke** [comment]
Windows uses pcre because that is what I build the installers with.
Other systems may use whatever regex library is available.

So, I would rather leave the sentence in the man page non-specific.
It is true that the Windows one is case-insensitive.

The example that you point at is not using regex delimiters, the slashes are directory markers.
For example, "/usr/bin/vim" is a file system path to the file named "vim".
If I wanted to match everything in the /usr/bin directory, I could have a regex "/bin/".
I could also have "/bin", or "bin", or "/usr/bin", all of which are valid but mean slightly different things.
Burp uses forward slashes for directories on all operating systems.

**Comment by juodumas** [comment]
Thanks for the explanation. So this is a mostly complete description of the exclude_regex feature:

    Exclude paths that match the regular expression. Case insensitive on Windows. Checked directories will always end with a forward slash. Uses PCRE on Windows and POSIX Extended Regular Expression syntax on other systems.

I believe that an extended description like this would be very useful to new users like me. Well, at least now this description of the `exclude_regex` keyword will be indexed by search engines.

**Comment by grke** [comment]
The description is not quite right, because non-Windows systems may use whatever regex library is available, which may not be POSIX.

**Comment by juodumas** [comment]
I didn't do proper testing, but I had `exclude_regex = /bak/$` and the bak directory didn't get excluded. Then I changed it to `exclude_regex = /bak$` and it worked.

**Pull request closed without merging**
