### PR TITLE
Backup tool script 0.4.6

### PR DESCRIPTION
**Pull request by deajan**
Log readability improvements and minor compat fixes for multiple OSes

### CODE REVIEW

**Comment by grke** [comment]
Thanks for this, I will merge it when I start branch 2.3.x.

**Comment by deajan** [comment]
Sure, I will continue improving it in the meantime :)

**Comment by deajan** [comment]
Updated with latest code than ran in production for two months.

**Comment by grke** [comment]
Thanks, will hopefully be merging for the next release in a couple of days.

**Pull request merged**
