### PR TITLE
[WIP] Autotools cleanup and conversion to Automake

### PR DESCRIPTION
**Pull request by rubenk**
Lots of stuff here. It works, tested it on a few platforms, but there's still some stuff that I had to break, notably:
- static binaries
- win32
- make check

I'm interested in any comment you may have.

### CODE REVIEW

**Comment by grke** [comment]
Hello,

I have checked out these changes, but I don't know what I should run to generate configure.
Everything I tried gave me errors. Can you tell me what I should run?

Other than that, I like that you deleted lots of useless things.

**Comment by rubenk** [comment]
`autoreconf -vif && ./configure` should be all that's needed.
if not, can you pastebin / gist the errors you get?

**Comment by grke** [comment]
OK, 'autoreconf -vif' worked to build the code.

To get utest to work in master, I do this:

make clean
./configure
cd utest
make

This doesn't work on FreeBSD. It works on Arch, Debian and Ubuntu.
With your changes above, I can get it to work (not on FreeBSD) by tweaking utest/Makefile to
set SYSCONFDIR. The utest/Makefile is not generated - it would be great to make it part of
the configure system like the other stuff, instead of the hacky stuff that I made.

**Comment by rubenk** [comment]
Ok, I did just that. The tests only go to a log file, not to stdout yet.

**Comment by rubenk** [comment]
Ah, wait, it works, and I just got an assertion on OSX :)
```
ruben@wodan: burp (autotools-02 %=)$ make check
Making check in src
Making check in manpages
make[1]: Nothing to be done for `check'.
Making check in utest
/Library/Developer/CommandLineTools/usr/bin/make  runner
make[2]: `runner' is up to date.
/Library/Developer/CommandLineTools/usr/bin/make  check-TESTS
Running suite(s): alloc
 attribs
 base64
 client_auth
 client_find
 client_monitor_json_input
 client_monitor_lline
 client_protocol1_backup_phase2
 client_protocol2_backup_phase2
 client_restore
 client_xattr
 cmd
 conf
 conffile
 fzp
 hexmap
 lock
 pathcmp
 protocol1_handy
 protocol1_rs_buf
 protocol2_blist
 protocol2_rabin_rconf
 protocol2_rabin_win
 sbuf_protocol2
 server_bu_get
 server_delete
 server_list
 server_manio
 server_monitor_browse
 server_monitor_cstat
 server_monitor_json_output
 server_protocol1_backup_phase2
 server_protocol1_bedup
 server_protocol1_blocklen
 server_protocol1_dpth
 server_protocol1_fdirs
 server_protocol2_backup_phase2
 server_protocol2_backup_phase4
 server_protocol2_champ_chooser_candidate
 server_protocol2_champ_chooser_champ_server
 server_protocol2_champ_chooser_dindex
 server_protocol2_champ_chooser_hash
 server_protocol2_champ_chooser_scores
 server_protocol2_champ_chooser_sparse
 server_protocol2_dpth
 server_restore
 server_resume
 server_sdirs
 slist
98%: Checks: 256, Failures: 3, Errors: 0
client/test_find.c:156:F:Core:test_find:0: Assertion '!mknod(tmp, mode, 100)' failed
client/protocol2/test_backup_phase2.c:205:F:Core:test_phase2_happy_path:0: Assertion 'backup_phase2_client_protocol2(asfd, confs, 0 )==expected_ret' failed
client/test_xattr.c:97:F:Core:test_xattrs:0: Assertion '!memcmp(x.expected_read, retrieved, rlen)' failed
FAIL: runner
==================
1 of 1 test failed
==================
make[2]: *** [check-TESTS] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
```

**Comment by rubenk** [comment]
Hi Graham,

Before I continue, I've got two more questions for you:
- What platforms do you expect Burp to run on? Apart from Linux, Windows, OSX and the BSD's, anything else like Solaris or AIX?
- What's the minimum requirement for a compiler? C99 / C++98?
I'm asking because if we can expect reasonably modern platforms we can drop a lot of autoconf checks.

**Comment by grkej** [comment]
The three utest failures:
client/test_find.c:156:F:Core:test_find:0: Assertion '!mknod(tmp, mode, 100)' failed

Probably OSX doesn't like trying to create nodes if you are not root.

client/protocol2/test_backup_phase2.c:205:F:Core:test_phase2_happy_path:0: Assertion 'backup_phase2_client_protocol2(asfd, confs, 0 )==expected_ret' failed

Don't know, though it is probably the same thing. Trying to create a socket or something as non-root.

client/test_xattr.c:97:F:Core:test_xattrs:0: Assertion '!memcmp(x.expected_read, retrieved, rlen)' failed

This one is probably a genuine problem.


I would like to add an OSX machine to my automated test system so that I can deal with these things faster, but I don't have a sensible way of doing so just now. I do have an OSX virtualbox that
I can hand test things on, but that is a pain.

**Comment by grkej** [comment]
"What platforms do you expect Burp to run on? Apart from Linux, Windows, OSX and the BSD's, anything else like Solaris or AIX?"

I would like it to not deliberately exclude anything.

However, I would say:
Linux
Windows
OSX
FreeBSD
OpenBSD
Solaris

I have used it on Solaris before, and always intended to add acl/xattr support for that - there is a github issue to make Solaris acl/xattr work somewhere in the list - but I don't mind that you've just
removed a bunch of stuff related to that.
I know nothing about AIX, and I don't recall anybody asking about it. Since nobody has asked about
it, I don't mind it not working.

In my automatic test system, I currently have four machines:
Ubuntu 64bit
Debian 32bit
Windows 2008 Server 64bit
FreeBSD 64bit
The most recent one I set up was FreeBSD. However, I had various problems running utest/test on it, so the only thing that the automated system does at the moment is run configure and gmake, nothing else. It would be really really good if your fixes could get utest/test working on the FreeBSD
machine, and then I will continue adding other machines to the array.
I also run my personal burp server on a Raspberry PI, with Debian.

**Comment by grkej** [comment]
"The most recent one I set up was FreeBSD. However, I had various problems running utest/test on it, so the only thing that the automated system does at the moment is run configure and gmake, nothing else."
By that, I meant all the other machines run all the tests (except no utest on Windows), and FreeBSD only does builds.

**Comment by grkej** [comment]
"What's the minimum requirement for a compiler? C99 / C++98? I'm asking because if we can expect reasonably modern platforms we can drop a lot of autoconf checks."

Sorry, I know nothing about minimum compiler requirements.
Reasonably modern platforms sound good to me.
If anybody is upset that their old compiler doesn't work, I think they can talk about it on the list.
If there are enough people that want it, we can think about putting it back in.

**Comment by grke** [comment]
Just noticed I have been signed in with my work account. Don't worry, grkej is me.

**Comment by rubenk** [comment]
Good morning Graham,

Thanks for your extensive replies.

As for the assertions, I'll look into the first two on OSX. The third one I was also able to hit on Fedora and FreeBSD.

As for running tests on OSX, have you looked into Travis? I know they have OSX builders and it's free for open source projects.

I tested these changes on Linux, FreeBSD, OpenBSD and NetBSD. The build on NetBSD is broken for different reasons, I'll file issues for those, but 'make check' works on the other platforms. `make check`  only runs the utest/ tests, but nothing in test/ yet.

As for the minimum compiler requirements, I was asking because for example, we check if intmax_t is defined, but all these types are guaranteed to exist by C99. But I now see we don't use the results of these checks anywhere, so I'll clean those up.

Another issue with the configure checks I noticed is that we check for them with a C compiler, but we compile with C++, so that can cause issues to and probably explains one of the failures I see on NetBSD.

One last question, how important are static builds of Burp? My distro of choice, Fedora, doesn't ship static libraries for the dependencies of burp, so if I want to test it I'll need to find something else.

All in all, lots to do, but this PR as is is looking pretty good, please give it a try as best as you can.

**Comment by rubenk** [comment]
I had to rebase so you might want to force pull.

**Comment by grke** [comment]
Hello,

I have personally found static builds useful in the past, and there is an item on the website FAQ about how to build them. However, I don't remember getting any mailing list messages from users about them.
I think that the number of things that you are fixing outweigh not having static builds, so that is OK.
I will try out the latest changes as soon as I can, which is hopefully tonight (it is early morning as I right this).

**Comment by rubenk** [comment]
Hi Graham,
Static linking with libstdc++ is a pain, so I'd rather not bother :)

Looking forward to your results.

**Comment by grke** [comment]
It is very nice that you can now compile utests and actual burp at the same time.

There are a few utests failing with 'make check'.
One is because of your change to the librsync block length code.
The others are all because the runner is running at the top level of the source, and it can't find the utest/json_output/ folder.

I see that the version is now in src/config.h, but you have it set to 2.0.8 instead of 2.0.28. Actually , that should be 2.0.29 for the current head, but I must have forgotten to update this month.

Building the windows installers with 'cd src/win32 && make && make WIN64=yes' works fine for me, once I have removed 3 remaining gettext _() things in src/win32/compat/mem_pool.c and src/win32/compat/compat.cpp.

**Comment by rubenk** [comment]
Hi Graham,

Ah, I'll look into fixing the runner. It seems to get srcdir as an environment variable:
"Test programs that need data files should look for them in srcdir (which is both a make variable and an environment variable made available to the tests)" (from
https://www.gnu.org/software/automake/manual/html_node/Scripts_002dbased-Testsuites.html#Scripts_002dbased-Testsuites)

It would also be nice if it did output the test  results in a format Automake could understand.

Great that src/win32 still builds. I'd love to integrate that into autotools to, but I'll have to do some reading about mingw since I never used it before. The nice thing is that Fedora has a complete Mingw64 environment.

**Comment by grke** [comment]
'cd test && make test' fails because the build_and_install script checks that build/src/burp exists, but the binary is now buillt directly at the top level.
Fixing that results in another failure because 'make install' seems to be not doing everything it needs
to do. The top level Makefile used to run the configs/install script, which did string replacements on the default configuration files. Maybe there is a proper way of doing this?

I think my lcov/gcov code coverage stuff has been deleted. I had hacked it into the bottom of the utest Makefile. I can hack it in somewhere else instead later, but it also needs the -lgcov linker flag on the utest runner in order to generate its files.

**Comment by grke** [comment]
Whenever I try to set up a mingw64 environment, it is a massive pain because all your binutils, gcc, etc, need to be the exact right versions. I think it is fine for you to leave it alone. :)

**Comment by rubenk** [comment]
Ok, I'll look into the 'make test' as well, and the gcov stuff. I'll leave win32 for what it is :)

**Comment by grke** [comment]
Overall, it looks very good.

It seems to be very close to a state in which I can merge and have my automated builds and tests keep working with a little bit of tweaking of scripts, and presumably my freebsd one will start being able to run tests instead of build only.

I think the 'make test' problem is just that configs/install doesn't run on 'make install'. It looks like the same problem will be true for a proper system 'make install'.
There is probably a proper way of doing what configs/install does that I don't know about.

**Comment by rubenk** [comment]
I was looking into the failure of one of the test cases:
```
$ CK_RUN_SUITE=client_xattr CK_TAP_LOG_FILE_NAME=- ./runner
Running suite(s): client_xattr
not ok 1 - utest/client/test_xattr.c:Core:test_xattrs: Assertion 'has_xattr(path)==0' failed
0%: Checks: 1, Failures: 1, Errors: 0
utest/client/test_xattr.c:80:F:Core:test_xattrs:0: Assertion 'has_xattr(path)==0' failed
1..1
```

This check fails because the file created has extended attributes. Turns out this is SELINUX:
```
$ ~/llistxattr utest_xattr/myfile 
security.selinux: unconfined_u:object_r:user_home_t:s0
```

Perhaps something to take into account?

**Comment by rubenk** [comment]
Hi Graham,

I might need your help since I'm a bit stuck. I noticed that 'make check' created a directory on my filesystem called (null). After a bit of digging, I found this is created by the test_proto2_stuff test in the server_restore suite.

The run_test function does
```
snprintf(path, sizeof(path), "%s/%s%s",
                               sdirs->currentdata, TREE_DIR, s->path.buf);
```
but at this point sdirs->currentdata is NULL.

I couldn't find how this is supposed to be filled, and if this a bug or not.

**Comment by grke** [comment]
I thought I had fixed that in a recent commit. You probably need to merge latest master.

**Comment by grke** [comment]
It was because the test should only make that path for PROTO_1 backups, I think.

**Comment by rubenk** [comment]
Thanks, I rebased and that did the trick.

I fixed up a lot of stuff today, could you please give it another go?

**Comment by grke** [comment]
I am unable to check it properly right now, but 'autoreconf -vif && cd test && make test' is failing because of something to do with the certificate exchange not working.

Also, rather than changing the paths in the scripts throughout the test directory, I was expecting to
just set options to 'configure' in 'build_and_install' to make them what the test scripts expect, like this:

./configure --prefix=/usr --sysconfdir=/etc/burp --localstatedir=/var

**Comment by rubenk** [comment]
I also got stuck on the certificate exchange, haven't really looked into it yet though.

Passing the paths to configure makes sense, let me rework that.

**Comment by rubenk** [comment]
With these latest changes I managed to let the tests run to completion.

**Comment by grke** [comment]
Nice, all the tests work for me too now.

I have two problems left:

autoreconf -vif
./configure --prefix=/usr --sysconfdir=/etc/burp
make

Then as root:
make install
Result:

make[1]: Entering directory '/home/graham/burp-ruben/burp'
 /usr/bin/mkdir -p '/usr/sbin'
 /usr/bin/install -c configs/certs/CA/burp_ca '/usr/sbin'
 /usr/bin/mkdir -p '/usr/sbin'
  /bin/sh ./libtool   --mode=install /usr/bin/install -c burp '/usr/sbin'
libtool: install: /usr/bin/install -c burp /usr/sbin/burp
 /usr/bin/mkdir -p '/etc/burp'
 /usr/bin/install -c -m 644 burp.conf burp-server.conf CA.cnf '/etc/burp'
 /usr/bin/mkdir -p '/etc/burp/clientconfdir'
 /usr/bin/install -c -m 644 configs/server/clientconfdir/incexc configs/server/clientconfdir/testclient '/etc/burp/clientconfdir'
/usr/bin/install: cannot overwrite directory ‘/etc/burp/clientconfdir/incexc’ with non-directory
Makefile:7366: recipe for target 'install-dist_clientconfDATA' failed
make[1]: *** [install-dist_clientconfDATA] Error 1
make[1]: Leaving directory '/home/graham/burp-ruben/burp'
Makefile:7828: recipe for target 'install-am' failed
make: *** [install-am] Error 2

I think the problem is that confs/server/clientconfdir/incexc used to end up as:
/etc/burp/clientconfdir/incexc/example, not /etc/burp/clientconfdir/incexc.
Renaming the file in the source to confs/server/clientconfdir/incexc/example would probably be the
best idea.


Also, previously, 'make install', which ran configs/install would not overwrite the following files if they already existed on the system. I think they are now being overwritten:

"$sysconfdir"/burp.conf
"$sysconfdir"/burp-server.conf
"$sysconfdir"/CA.cnf
"$sysconfdir"/clientconfdir/incexc/example 
"$sysconfdir"/clientconfdir/testclient
"$sysconfdir"/clientconfdir/incexc/example
"$sysconfdir"/autoupgrade/server/win32/script
"$sysconfdir"/autoupgrade/server/win64/script
"$scriptdir"/notify_script
"$scriptdir"/summary_script
"$scriptdir"/timer_script
"$scriptdir"/ssl_extra_checks_script

If making them not get overwritten is difficult, or not something that is normal to do, that is OK, I will
just have to put warnings in the notes for the next release.

**Comment by rubenk** [comment]
I fixed the first issue,

Make install always overwrites files, and working around it is indeed hard to do and not done often.

**Comment by grke** [comment]
Great, I am going to merge this now and then get it working fully on my automatic testing system.
Thanks for your excellent work!

**Comment by grke** [comment]
I have a problem on my debian i386 machine.
First, 'autoreconf -vif' complained that configure.ac needed 'AC_PROG_CC' because it found C files, so I added that. Then 'configure' complained that there was a syntax error near to 'LT_INIT([disable-static])', so I deleted that line from configure.ac and started again.

This time, 'configure' completed, but then 'make check' fails with what looks like a problem where it can't link to libcheck. There are lots of messages like this:

/home/grke/burp-2.0.29/utest/server/test_sdirs.c:154: undefined reference to `tcase_fn_start'
utest/server/runner-test_sdirs.o: In function `protocol1_tests':
/home/grke/burp-2.0.29/utest/server/test_sdirs.c:83: undefined reference to `_ck_assert_msg'
/home/grke/burp-2.0.29/utest/server/test_sdirs.c:84: undefined reference to `_ck_assert_msg'
/home/grke/burp-2.0.29/utest/server/test_sdirs.c:85: undefined reference to `_ck_assert_msg'
/home/grke/burp-2.0.29/utest/server/test_sdirs.c:86: undefined reference to `_ck_assert_msg'
/home/grke/burp-2.0.29/utest/server/test_sdirs.c:87: undefined reference to `_ck_assert_msg'
utest/server/runner-test_sdirs.o:/home/grke/burp-2.0.29/utest/server/test_sdirs.c:88: more undefined references to `_ck_assert_msg' follow
utest/server/runner-test_sdirs.o: In function `suite_server_sdirs()':
/home/grke/burp-2.0.29/utest/server/test_sdirs.c:184: undefined reference to `suite_create'
/home/grke/burp-2.0.29/utest/server/test_sdirs.c:186: undefined reference to `tcase_create'
/home/grke/burp-2.0.29/utest/server/test_sdirs.c:188: undefined reference to `_tcase_add_test'
/home/grke/burp-2.0.29/utest/server/test_sdirs.c:189: undefined reference to `_tcase_add_test'
/home/grke/burp-2.0.29/utest/server/test_sdirs.c:190: undefined reference to `suite_add_tcase'
collect2: error: ld returned 1 exit status
Makefile:2203: recipe for target 'runner' failed
make: *** [runner] Error 1

Any idea how to fix that?

**Comment by grke** [comment]
Hmm, also happening on my ubuntu 64 bit machine. Works fine on my arch desktop.

**Comment by rubenk** [comment]
Which Debian and Ubuntu versions is this happening on? I'll see if I can reproduce it. Perhaps your libtool is too old.

Btw, by removing LT_INIT([disable-static]) you removed libtool support, I'm not entirely surprised that this made the tests fail ;)

**Comment by grke** [comment]
Debian version is 8.2.

**Comment by grke** [comment]
Ubuntu version is 14.04.2 LTS.

**Comment by rubenk** [comment]
Does configure detect Check on both machines?

**Comment by grke** [comment]
I reverted any changes that I made. On Debian:
./configure: line 5492: syntax error near unexpected token `disable-static'
./configure: line 5492: `LT_INIT(disable-static)'

On Ubuntu, configure finishes OK, then 'make check' ends in the check linking errors.
I cannot tell if configure detected the check library. If I do a 'grep -r CHECK_LIBS *' after configure,
the output is this:
ubuntu@ip-172-31-9-216:~/burp-2.0.29$ grep -r CHECK_LIBS *
Makefile:       $(CHECK_LIBS) \
Makefile.am:    $(CHECK_LIBS) \
Makefile.in:    $(CHECK_LIBS) \
So, it looks like it has not detected it, as nothing defines it anywhere.

Going back to Debian, 'configure' works if I use 'LT_INIT()', but 'make check' fails like this:
  CC       utest/client/runner-test_xattr.o
In file included from utest/client/../test.h:6:0,
                 from utest/client/test_xattr.c:1:
utest/client/test_xattr.c: In function ‘void test_xattr(xattrdata)’:
utest/client/test_xattr.c:80:28: error: ‘has_xattr’ was not declared in this scope
  fail_unless(has_xattr(path)==0);
                            ^
utest/client/test_xattr.c:88:2: error: ‘set_xattr’ was not declared in this scope
  ));
  ^
utest/client/test_xattr.c:95:2: error: ‘get_xattr’ was not declared in this scope
  ));
  ^
Makefile:5025: recipe for target 'utest/client/runner-test_xattr.o' failed
make[1]: *** [utest/client/runner-test_xattr.o] Error 1
make[1]: Leaving directory '/home/grke/burp-2.0.29'
Makefile:7760: recipe for target 'check-am' failed
make: *** [check-am] Error 2

This is also strange, as 'configure' said 'xattr: yes'.

**Comment by rubenk** [comment]
I just installed a fresh Debian 8.2 vm, but I can't reproduce it. I get not a single warning from autoreconf -vif. ./configure && make && make check work fine.

All I did was `apt-get install autoconf automake libtool make pkg-config check libssl-dev liibrsync-dev uthash-dev g++`. You might be either missing one of these, or there's some old cruft in your source dir. Have you tried a clean checkout?

**Comment by grke** [comment]
OK, I ran that apt-get command (with correct librsync-dev spelling), and some libtool files were updated. It now works on both machines, compiling and linking OK.

Sorry for the noise, and thanks for the hints.

**Comment by rubenk** [comment]
Ah great, glad that it works, and thanks for merging!

**Pull request merged**
